# Example of quadratic programming

In [101]:
# install cvxopt library
#!conda install cvxopt     # 파워쉘을 이용하여 수행하면 시간이 훨씬 절약된다.

In [102]:
import numpy as np
from cvxopt import matrix, solvers

In [103]:
 X = np.array([[1, 6], [1, 8], [4, 11], [5, 2], [7, 6], [9, 3]], dtype=np.float64)

In [104]:
t = np.array([[1], [1], [1], [-1], [-1], [-1]], dtype=np.float64)

In [105]:
X_square = np.matmul(X, np.transpose(X)) 

In [106]:
t_square = np.matmul(t, np.transpose(t)) 

In [107]:
H = (X_square * t_square)
print(H)

[[ 37.  49.  70. -17. -43. -27.]
 [ 49.  65.  92. -21. -55. -33.]
 [ 70.  92. 137. -42. -94. -69.]
 [-17. -21. -42.  29.  47.  51.]
 [-43. -55. -94.  47.  85.  81.]
 [-27. -33. -69.  51.  81.  90.]]


In [108]:
H = matrix(H)
f = matrix(-np.ones((6,1), dtype=np.float64))
A = matrix(-np.eye(6, dtype=np.float64))
a = matrix(np.zeros((6,1), dtype=np.float64))
B = matrix(np.transpose(t))
b = matrix(np.array([0.]))

In [109]:
solvers.options['show_progress'] = False
sol = solvers.qp(H, f, A, a, B, b)
alphas = np.array(sol['x'])

In [110]:
print(np.round_(alphas, 5))      # 소숫점 5자리이하 반올림

[[0.03556]
 [0.     ]
 [0.04   ]
 [0.     ]
 [0.07556]
 [0.     ]]
